### PR TITLE
[FIX] - Verified attributes added to response

### LINKED ISSUE #13: attributes by agreement
La chiamata a /agreements/{agreementId}/attributes con 
agreementId = 65328879-c1c3-4ca8-88e8-81aac323a8bd

non ritorna attributi nonostante questi siano stati verificati

### PR DESCRIPTION
**Pull request by ubaldop**
This fixes #13.

### CODE REVIEW

File: src/main/scala/it/pagopa/interop/apigateway/api/impl/package.scala [hunk 1]
```diff
@@ -143,10 +144,8 @@ package object impl extends SprayJsonSupport with DefaultJsonProtocol {
       EService(eservice.id, eservice.name, version = descriptor.version, state = descriptor.state.toModel)
 
     private def flatAttributes(attribute: CatalogManagementApiAttribute): Set[UUID] = {
-      val flattenAttributes: Option[Seq[String]] = for {
```
Comment (ubaldop) [inline src/main/scala/it/pagopa/interop/apigateway/api/impl/package.scala:146]: originally we made a for comprehension because the ADT modeling of Attribute does not expose the implicit invariant that it MUST be either a single or a group attribute, not both.
Because of that, this was always reduced to None.

Possible improvement there: could `Attribute` be a Sum type instead?

Comment (beetlecrunch) [reply src/main/scala/it/pagopa/interop/apigateway/api/impl/package.scala:146]: It could be a sum type only in the internal model.
At API level we can't implement it as ADT because the "oneOf" keyword is not managed by the openapi generator.

**Review by galales — APPROVED** [review]

File: src/main/scala/it/pagopa/interop/apigateway/api/impl/package.scala [hunk 2]
```diff
@@ -143,10 +144,8 @@ package object impl extends SprayJsonSupport with DefaultJsonProtocol {
       EService(eservice.id, eservice.name, version = descriptor.version, state = descriptor.state.toModel)
 
     private def flatAttributes(attribute: CatalogManagementApiAttribute): Set[UUID] = {
```
Comment (TonioGela) [inline src/main/scala/it/pagopa/interop/apigateway/api/impl/package.scala]: I would replace this whole method implementation with this one:
```scala
private def flatAttributes(attribute: CatalogManagementApiAttribute): Set[UUID] =
(attribute.group.sequence :+ attribute.single).flatten.traverse(_.id.toUUID).getOrElse(List.empty).toSet
```
that is IMHO more clear and passes tests

**Review by TonioGela — CHANGES_REQUESTED** [review]

File: src/main/scala/it/pagopa/interop/apigateway/api/impl/package.scala (hunk 1 above)
Comment (ubaldop) [reply src/main/scala/it/pagopa/interop/apigateway/api/impl/package.scala:146]: 🆗

File: src/main/scala/it/pagopa/interop/apigateway/api/impl/package.scala (hunk 2 above)
Comment (ubaldop) [reply src/main/scala/it/pagopa/interop/apigateway/api/impl/package.scala]: ok

**Review by TonioGela — APPROVED** [review]
